---
- name: Add mesosphere repo
  yum: name={{ mesosphere_repo }} state=present

- name: Install Marathon
  yum: name={{ item }} state=present
  with_items:
    - mesos
    - marathon-{{ marathon_version }}